### ISSUE TITLE
Input/output error with i2c_rdwr

### ISSUE THREAD

**Issue by daylanKifky** [kplindegaard/smbus2#65]
Hi! 
I'm trying to do a simple read using `i2c_rdwr`, In a Raspeberry pi 3 with Raspbian stretch but I get this error:

```none
Traceback (most recent call last):
  File "i2c_test.py", line 8, in <module>
    i2cbus.i2c_rdwr(read)
  File "/home/pi/.local/lib/python3.5/site-packages/smbus2/smbus2.py", line 658, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
OSError: [Errno 5] Input/output error
```

I checked the `I2C_FUNC_I2C` capabilities and they should be OK
This is a minmal example that reproduces the problem: 

```
from smbus2 import SMBus, i2c_msg, I2cFunc

i2cbus = SMBus(1)  # Create a new I2C bus
i2caddress = 0x40

if (i2cbus._get_funcs() & I2cFunc.I2C):
	read = i2c_msg.read(i2caddress, 9)
	i2cbus.i2c_rdwr(read)
	data = list(read)
	print(data)
else:
	#from https://www.kernel.org/doc/html/latest/i2c/dev-interface.html#full-interface-description
	print("The i2c adapter doesn't support RDWR")
```

Any ideas?
Thanks in advance

**Comment by daylanKifky** [comment]
After further testing the problem was at the slave end of the communication, so it has nothing to do with this library
